-- Database Creation Script for Team14_DB
-- Generated from ERD specifications

-- Use the Team14_DB schema
USE Team14_DB;

-- Drop tables if they exist (in reverse order of dependencies)
DROP TABLE IF EXISTS Applications;
DROP TABLE IF EXISTS PointRules;
DROP TABLE IF EXISTS Carts;
DROP TABLE IF EXISTS AuditLog;
DROP TABLE IF EXISTS PointLog;
DROP TABLE IF EXISTS Notifications;
DROP TABLE IF EXISTS DriverInvitations;
DROP TABLE IF EXISTS UserOrganizations;
DROP TABLE IF EXISTS Reports;
DROP TABLE IF EXISTS About;
DROP TABLE IF EXISTS Organizations;
DROP TABLE IF EXISTS Users;

-- Create Users table
CREATE TABLE Users (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    F_NAME VARCHAR(100) NOT NULL,
    L_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    POINT_TOTAL INT DEFAULT 0,
    USER_TYPE ENUM('admin', 'sponsor', 'driver') NOT NULL,
    RESET_TOKEN VARCHAR(255),
    RESET_TOKEN_EXPIRY DATETIME,
    INDEX idx_email (EMAIL),
    INDEX idx_username (USERNAME)
);

-- Create Organizations table
CREATE TABLE Organizations (
    ORG_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORG_LEADER_ID INT,
    ORG_NAME VARCHAR(255) NOT NULL,
    product1 INT,
    product2 INT,
    product3 INT,
    product4 INT,
    product5 INT,
    INDEX idx_org_leader (ORG_LEADER_ID),
    FOREIGN KEY (ORG_LEADER_ID) REFERENCES Users(USER_ID) ON DELETE SET NULL
);

-- Create UserOrganizations junction table
CREATE TABLE UserOrganizations (
    USER_ID INT NOT NULL,
    ORG_ID INT NOT NULL,
    POINT_TOTAL INT DEFAULT 0,
    PRIMARY KEY (USER_ID, ORG_ID),
    INDEX idx_user (USER_ID),
    INDEX idx_org (ORG_ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ORG_ID) REFERENCES Organizations(ORG_ID) ON DELETE CASCADE
);

-- Create DriverInvitations table
CREATE TABLE DriverInvitations (
    INVITE_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    ORG_ID INT NOT NULL,
    INVITE_TOKEN VARCHAR(64) NOT NULL UNIQUE,
    INVITED_BY INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USED_AT TIMESTAMP NULL,
    INDEX idx_token (INVITE_TOKEN),
    INDEX idx_org (ORG_ID),
    FOREIGN KEY (ORG_ID) REFERENCES Organizations(ORG_ID) ON DELETE CASCADE,
    FOREIGN KEY (INVITED_BY) REFERENCES Users(USER_ID) ON DELETE CASCADE
);

-- Create Notifications table
CREATE TABLE Notifications (
    NOTIF_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOTIF_TYPE VARCHAR(100) NOT NULL,
    NOTIF_CONTENT VARCHAR(100) NOT NULL,
    USER_ID INT NOT NULL,
    INDEX idx_user (USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE
);

-- Create PointLog table
CREATE TABLE PointLog (
    TRANS_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    DATE_CHANGED VARCHAR(100) NOT NULL,
    INDEX idx_user (USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE
);

-- Create AuditLog table
CREATE TABLE AuditLog (
    LOG_TYPE VARCHAR(100) NOT NULL,
    TRANS_ID INT NOT NULL,
    LOG_DATE VARCHAR(100) NOT NULL,
    USER_ID INT NOT NULL,
    INDEX idx_trans (TRANS_ID),
    INDEX idx_user (USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE
);

-- Create Reports table
CREATE TABLE Reports (
    REPORT_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORG_ID INT NOT NULL,
    INDEX idx_org (ORG_ID),
    FOREIGN KEY (ORG_ID) REFERENCES Organizations(ORG_ID) ON DELETE CASCADE
);

-- Create About table
CREATE TABLE About (
    TEAM INT PRIMARY KEY,
    SPRINT INT NOT NULL,
    RELEASE_DATE VARCHAR(100) NOT NULL,
    PROD_NAME VARCHAR(100) NOT NULL,
    PROD_DESC VARCHAR(100) NOT NULL
);

-- Create Carts table
CREATE TABLE Carts (
    USER_ID INT NOT NULL,
    ORG_ID INT NOT NULL,
    ITEMS_JSON JSON NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, ORG_ID),
    INDEX idx_user (USER_ID),
    INDEX idx_org (ORG_ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ORG_ID) REFERENCES Organizations(ORG_ID) ON DELETE CASCADE
);

-- Create PointRules table
CREATE TABLE PointRules (
    RULE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORG_ID INT NOT NULL,
    RULE_TYPE VARCHAR(100) NOT NULL,
    PT_CHANGE INT NOT NULL,
    INDEX idx_org (ORG_ID),
    FOREIGN KEY (ORG_ID) REFERENCES Organizations(ORG_ID) ON DELETE CASCADE
);

-- Create Applications table
CREATE TABLE Applications (
    APP_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORG_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    INDEX idx_org (ORG_ID),
    INDEX idx_user (USER_ID),
    FOREIGN KEY (ORG_ID) REFERENCES Organizations(ORG_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID) ON DELETE CASCADE
);

